import Head from "next/head";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div
        style={{
          backgroundColor: "gray",
          width: "100vw",
          height: "100vh",
        }}
      >
        <button onClick={() => router.push("/profile")}>profile</button>
        <h2 onClick={() => router.push("/about")}>about</h2>
        <h2 onClick={() => router.push("/blog")}>blog</h2>
        <h2 onClick={() => router.push("/blog1")}>blog1</h2>
        <h2 onClick={() => router.push("/blog2")}>blog2</h2>
        <h2 onClick={() => router.push("/sakhfjkafds")}>404</h2>
      </div>
      
    </div>
  );
}
