import { useRouter } from "next/router";
import Head from "next/head";

export default function Home() {
  const router = useRouter();

  return (
    <div>
      <Head>
        <title>ShubhamS Next App</title>
        <meta
          name="description"
          content="Generated by shubham to create next seo"
        />
        <meta />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        style={{
          backgroundColor: "gray",
          width: "100vw",
          height: "100vh",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <h1>Next</h1>
        <button onClick={() => router.push("/profile")}>profile</button>
        <h2 onClick={() => router.push("/about")}>about</h2>
        <h2 onClick={() => router.push("/blog")}>blog</h2>
        <h2 onClick={() => router.push("/blog/blog1")}>blog11</h2>
        <h2 onClick={() => router.push("/blog/blog2")}>blog22</h2>
        <h2 onClick={() => router.push("/sakhfjkafds")}>404</h2>
      </div>
    </div>
  );
}
